local:
  hosts:
    servidor1:
      ansible_host: localhost
      ansible_port: 5001
      ansible_ssh_private_key_file: "~/.ssh/ifmt_ed25519"
      ansible_python_interpreter: "/usr/bin/python3.12"
      
    servidor2:
      ansible_host: localhost
      ansible_port: 5002
      ansible_ssh_private_key_file: "~/.ssh/ifmt_ed25519"
      ansible_python_interpreter: "/usr/bin/python3.12"

    servidor3:
      ansible_host: localhost
      ansible_port: 5003
      ansible_ssh_private_key_file: "~/.ssh/ifmt_ed25519"
      ansible_python_interpreter: "/usr/bin/python3.12"
